name: Unit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make develop
      - name: Test
        run: make test
        shell: bash -el {0}

      - name: Publish test results
        uses: actions/upload-artifact@v3
        with:
          name: Test results
          path: test-data.xml

      - name: Report Coverage
        run: coverage report -m
        shell: bash -el {0}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-farkle
          fail_ci_if_error: true
          verbose: true
